-- MySQL Script generated by MySQL Workbench
-- Mon Jul 26 20:26:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruebafinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruebafinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebafinal` DEFAULT CHARACTER SET utf8 ;
USE `pruebafinal` ;

-- -----------------------------------------------------
-- Table `pruebafinal`.`ejecutivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebafinal`.`ejecutivo` (
  `rut` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebafinal`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebafinal`.`cliente` (
  `rut` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `ejecutivo_rut` VARCHAR(20) NULL,
  PRIMARY KEY (`rut`),
  CONSTRAINT `fk_cliente_ejecutivo`
    FOREIGN KEY (`ejecutivo_rut`)
    REFERENCES `pruebafinal`.`ejecutivo` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_ejecutivo_idx` ON `pruebafinal`.`cliente` (`ejecutivo_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pruebafinal`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebafinal`.`mensaje` (
  `idmensaje` INT NOT NULL,
  `asunto` VARCHAR(20) NULL,
  `contenido` VARCHAR(200) NULL,
  `respuesta` VARCHAR(200) NULL,
  `cliente_rut` VARCHAR(20) NULL,
  `ejecutivo_rut` VARCHAR(20) NULL,
  PRIMARY KEY (`idmensaje`),
  CONSTRAINT `fk_mensaje_cliente1`
    FOREIGN KEY (`cliente_rut`)
    REFERENCES `pruebafinal`.`cliente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_ejecutivo1`
    FOREIGN KEY (`ejecutivo_rut`)
    REFERENCES `pruebafinal`.`ejecutivo` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mensaje_cliente1_idx` ON `pruebafinal`.`mensaje` (`cliente_rut` ASC) VISIBLE;

CREATE INDEX `fk_mensaje_ejecutivo1_idx` ON `pruebafinal`.`mensaje` (`ejecutivo_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pruebafinal`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebafinal`.`cuenta` (
  `idcuenta` INT NOT NULL,
  `saldo` INT NULL,
  `claveTransaccion` INT NULL,
  `saldoLineaCredito` INT NULL,
  `saldoLineaCreditoUsado` INT NULL,
  `estado` INT NULL,
  `cliente_rut` VARCHAR(20) NULL,
  PRIMARY KEY (`idcuenta`),
  CONSTRAINT `fk_cuenta_cliente1`
    FOREIGN KEY (`cliente_rut`)
    REFERENCES `pruebafinal`.`cliente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cuenta_cliente1_idx` ON `pruebafinal`.`cuenta` (`cliente_rut` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pruebafinal`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebafinal`.`movimientos` (
  `idmovimientos` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `cuenta_idcuenta` INT NULL,
  PRIMARY KEY (`idmovimientos`),
  CONSTRAINT `fk_movimientos_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `pruebafinal`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_movimientos_cuenta1_idx` ON `pruebafinal`.`movimientos` (`cuenta_idcuenta` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
